CREATE (a:Author{name:'Renata Cristina Faray Melo', gender: 'F'});
CREATE (a:Author{name:'Marcelo Nardelli Pinto Santana', gender: 'M'});
CREATE (a:Author{name:'Rodolfo Bezerra Batista', gender: 'M'});
CREATE (a:Author{name:'Edward Ribeiro', gender: 'M'});
CREATE (a:Author{name:'Gustavo Zerlotini', gender: 'M'});
CREATE (a:Author{name:'Irving Lopes', gender: 'M'});
CREATE (a:Author{name:'Vitor Ribeiro', gender: 'M'});
CREATE (a:Author{name:'Marcos Mota Costa', gender: 'M'});
CREATE (a:Author{name:'Marcos Vinicius Pinheiro Dib', gender: 'M'});
CREATE (a:Author{name:'Cláudio Jorge Pinto Alves', gender: 'M'});
CREATE (a:Author{name:'Azzedine Boukerche', gender: 'M'});
CREATE (a:Author{name:'Edans Flavius De Oliveira Sandes', gender: '?'});
CREATE (a:Author{name:'Antonio Marcio Ferreira Crespo', gender: 'M'});
CREATE (a:Author{name:'Carlos Vuyk De Aquino', gender: 'M'});
CREATE (a:Author{name:'Bueno B. De Souza', gender: 'M'});
CREATE (a:Author{name:'Victor Rafael Rezende Celestino', gender: 'M'});
CREATE (a:Author{name:'Jan Mendonca Correa', gender: 'M'});
CREATE (a:Author{name:'Marcelo Silva Sousa', gender: 'M'});
CREATE (a:Author{name:'Felipe Brandt Scarel', gender: 'M'});
CREATE (a:Author{name:'Lavir Antonio Bahia Carvalho De Souza', gender: 'M'});
CREATE (a:Author{name:'Juan Fernando Eusse', gender: 'M'});
CREATE (a:Author{name:'Nahri Moreano', gender: '?'});
CREATE (a:Author{name:'Alessandro Ferreira Leite', gender: 'M'});
CREATE (a:Author{name:'Hammurabi Das Chagas Mendes', gender: '?'});
CREATE (a:Author{name:'Khaled Hamidouche', gender: 'M'});
CREATE (a:Author{name:'Fernando Machado Mendonça', gender: 'M'});
CREATE (a:Author{name:'Joel Falcou', gender: 'M'});
CREATE (a:Author{name:'Daniel Etiemble', gender: 'M'});
CREATE (a:Author{name:'Emerson De Araujo Macedo', gender: 'M'});
CREATE (a:Author{name:'Gerson Henrique Pfitscher', gender: 'M'});
CREATE (a:Author{name:'Jianya Zheng', gender: '?'});
CREATE (a:Author{name:'Lorna Uden', gender: 'F'});
CREATE (a:Author{name:'Guillermo Miranda', gender: 'M'});
CREATE (a:Author{name:'Eduard Ayguade', gender: 'M'});
CREATE (a:Author{name:'Xavier Martorell', gender: 'M'});
CREATE (a:Author{name:'Daniel Sundfeld', gender: 'M'});
CREATE (a:Author{name:'Jakob Hull Havgaard', gender: 'M'});
CREATE (a:Author{name:'Jan Gorodkin', gender: 'M'});
CREATE (a:Author{name:'Christine Eisenbeis', gender: 'F'});
CREATE (a:Author{name:'Claude Tadonki', gender: 'M'});
CREATE (a:Author{name:'Tahsin M. Kurç', gender: 'M'});
CREATE (a:Author{name:'Luís F R Taveira', gender: 'M'});
CREATE (a:Author{name:'Yi Gao', gender: '?'});
CREATE (a:Author{name:'Jun Kong', gender: 'M'});
CREATE (a:Author{name:'Joel Saltz', gender: 'M'});
CREATE (a:Author{name:'Caina Razzolini', gender: 'M'});
CREATE (a:Author{name:'Vander Alves', gender: 'M'});
CREATE (a:Author{name:'Gustavo Portella', gender: 'M'});
CREATE (a:Author{name:'Eduardo Yoshio Nakano', gender: 'M'});
CREATE (a:Author{name:'Jeremias Moreira Gomes', gender: 'M'});
CREATE (a:Author{name:'Marco Antonio Caldas De Figueiredo Jr', gender: 'M'});
CREATE (a:Author{name:'Erich Bremer', gender: 'M'});
CREATE (a:Author{name:'Jesús Pérez-serrano', gender: 'M'});
CREATE (a:Author{name:'Manuel Ujaldon', gender: 'M'});
CREATE (a:Author{name:'Aldo Henrique Dias Mendes', gender: 'M'});
CREATE (a:Author{name:'Luiz Laranjeira', gender: 'M'});
CREATE (a:Author{name:'Willian De Oliveira Barreiros Júnior', gender: 'M'});
CREATE (a:Author{name:'Gabriel H. G. Silva', gender: 'M'});
CREATE (a:Author{name:'Carlos A. C. Jorge', gender: 'M'});
CREATE (a:Author{name:'Alexandre Solon Nery', gender: 'M'});
CREATE (a:Author{name:'Alfredo Goldman', gender: 'M'});
CREATE (a:Author{name:'Joao Paulo Navarro', gender: 'M'});
CREATE (a:Author{name:'Renato Fontes Guimarães', gender: 'M'});
CREATE (a:Author{name:'Felipe Pontes Guimarães', gender: 'M'});
CREATE (a:Author{name:'Pedro Célestin', gender: 'M'});
CREATE (a:Author{name:'Daniel Macedo Batista', gender: 'M'});
CREATE (a:Author{name:'Cristina Boeres', gender: 'F'});
CREATE (a:Author{name:'Vinod E.f. Rebello', gender: 'M'});
CREATE (a:Author{name:'Celso C. Ribeiro', gender: 'M'});
CREATE (a:Author{name:'Pedro Garcia Freitas', gender: 'M'});
CREATE (a:Author{name:'Eduardo Henrique Teixeira', gender: 'M'});
CREATE (a:Author{name:'José Benedito De Souza Brito', gender: 'M'});
CREATE (a:Author{name:'Guilherme Vergara', gender: 'M'});
CREATE (a:Author{name:'Michel J.f.rosa', gender: 'M'});
CREATE (a:Author{name:'Breno R. Moura', gender: 'M'});
CREATE (a:Author{name:'Antonio M. A. Ferreira', gender: 'M'});
CREATE (a:Author{name:'Sergio Lifschitz', gender: 'M'});
CREATE (a:Author{name:'Waldeyr Mendes Cordeiro Da Silva', gender: 'M'});
CREATE (a:Author{name:'Klayton Castro', gender: 'M'});
CREATE (a:Author{name:'Polyane Wercelens', gender: 'F'});
CREATE (a:Author{name:'Fernanda Hondo', gender: 'F'});
CREATE (a:Author{name:'Guilherme Novaes Ramos', gender: 'M'});
CREATE (a:Author{name:'George Von Borries', gender: 'M'});
CREATE (a:Author{name:'Roberto Mourão', gender: 'M'});
CREATE (a:Author{name:'João Bachiega Junior', gender: 'M'});
CREATE (a:Author{name:'Breno G. S. Costa', gender: 'M'});
CREATE (a:Author{name:'Leonardo Rebouças De Carvalho', gender: 'M'});
CREATE (a:Author{name:'Nelson Luis Saldanha Da Fonseca', gender: 'M'});
CREATE (a:Author{name:'Mike Devetsikiotis', gender: 'M'});
CREATE (a:Author{name:'Sávio R. A. Dos Santos Rosa', gender: 'M'});
CREATE (a:Author{name:'Xiaomin Chen', gender: '?'});
CREATE (a:Author{name:'Admela Jukan', gender: '?'});
CREATE (a:Author{name:'Alisson S. L. Pontes', gender: 'F'});
CREATE (a:Author{name:'Juliana De Santi', gender: 'F'});
CREATE (a:Author{name:'Lucas Rodrigues Costa', gender: 'M'});
CREATE (a:Author{name:'Rafael F. Santos', gender: 'M'});
CREATE (a:Author{name:'Alessandro Andrioni', gender: 'M'});
CREATE (a:Author{name:'Eduardo Candido Xavier', gender: 'M'});
CREATE (a:Author{name:'Alexandre Lucchesi', gender: 'M'});
CREATE (a:Author{name:'Paulo Angelo Alves Resende', gender: 'M'});
CREATE (a:Author{name:'Ítalo Barbosa Brasileiro', gender: 'M'});
CREATE (a:Author{name:'Marcelino Monteiro De Andrade', gender: 'M'});
CREATE (a:Author{name:'Francisco Assis De Oliveira Nascimento', gender: 'M'});
CREATE (a:Author{name:'Adson F. Da Rocha', gender: 'M'});
CREATE (a:Author{name:'Daniel F. Vasconcelos', gender: 'M'});
CREATE (a:Author{name:'Paulo César De Jesus', gender: 'M'});
CREATE (a:Author{name:'Hervaldo Sampaio Carvalho', gender: 'M'});
CREATE (a:Author{name:'Fernanda Brandi', gender: 'F'});
CREATE (a:Author{name:'Eduardo Peixoto', gender: 'M'});
CREATE (a:Author{name:'Debargha Mukherjee', gender: '?'});
CREATE (a:Author{name:'João Yoshiyuki Ishihara', gender: 'M'});
CREATE (a:Author{name:'Marco Henrique Terra', gender: 'M'});
CREATE (a:Author{name:'Salvador A Melo Júnior', gender: 'M'});
CREATE (a:Author{name:'João Luiz Azevedo De Carvalho', gender: 'M'});
CREATE (a:Author{name:'Pedro De Azevedo Berger', gender: 'M'});
CREATE (a:Author{name:'Adson Ferreira Da Rocha', gender: 'M'});
CREATE (a:Author{name:'Carolina Gonçalves Abreu', gender: 'F'});
CREATE (a:Author{name:'Cássio Giorgio Couto Coelho', gender: 'M'});
CREATE (a:Author{name:'Alexandre Zaghetto', gender: 'M'});
CREATE (a:Author{name:'Ricardo Machado', gender: 'M'});
CREATE (a:Author{name:'Edson Mintsu Hung', gender: 'M'});
CREATE (a:Author{name:'Gene Cheung', gender: 'F'});
CREATE (a:Author{name:'Tan Wai-tian', gender: 'M'});
CREATE (a:Author{name:'Nilson Donizete Guerin', gender: 'M'});
CREATE (a:Author{name:'Marcel H. Trabuco', gender: 'M'});
CREATE (a:Author{name:'Marcus V. C. Costa', gender: 'M'});
CREATE (a:Author{name:'Davi Benevides Gusmão', gender: 'M'});
CREATE (a:Author{name:'Montse Pardàs', gender: 'F'});
CREATE (a:Author{name:'Ferran Marqués', gender: 'M'});
CREATE (a:Author{name:'Diogo Caetano Garcia', gender: 'M'});
CREATE (a:Author{name:'Renan U. Ferreira', gender: 'F'});
CREATE (a:Author{name:'Davi R. Freitas', gender: 'M'});
CREATE (a:Author{name:'Rogerio Higa', gender: 'M'});
CREATE (a:Author{name:'Ismael Seidel', gender: 'M'});
CREATE (a:Author{name:'Vanessa Testoni', gender: 'F'});
CREATE (a:Author{name:'Clare Dixon', gender: 'F'});
CREATE (a:Author{name:'Michael Fisher', gender: 'M'});
CREATE (a:Author{name:'Lan Zhang', gender: 'M'});
CREATE (a:Author{name:'Ullrich Hustadt', gender: 'M'});
CREATE (a:Author{name:'Oliver Kutz', gender: 'M'});
CREATE (a:Author{name:'Bruno L. Dalmazo', gender: 'M'});
CREATE (a:Author{name:'Gilles Dowek', gender: 'M'});
CREATE (a:Author{name:'Edward Hermann Haeusler', gender: 'M'});
CREATE (a:Author{name:'Joao Marcos De Almeida', gender: 'M'});
CREATE (a:Author{name:'José Carlos Loureiro Ralha', gender: 'M'});
CREATE (a:Author{name:'Flávio Maico Vaz Da Costa', gender: 'M'});
CREATE (a:Author{name:'Ana Regia De Mendonça Neves', gender: 'F'});
CREATE (a:Author{name:'Humphrey Corrêa Da Fonseca', gender: 'M'});
CREATE (a:Author{name:'Letícia T. Maia Zoby', gender: 'F'});
CREATE (a:Author{name:'Carlos Vinícius Sarmento Silva', gender: 'M'});
CREATE (a:Author{name:'Georger Rommel Ferreira De Araújo', gender: 'M'});
CREATE (a:Author{name:'Diogo R. Ferreira', gender: 'M'});
CREATE (a:Author{name:'Fernando Szimanski', gender: 'M'});
CREATE (a:Author{name:'Alvaro Marcos Guarieiro Carvalho', gender: 'M'});
CREATE (a:Author{name:'Denise Bomtempo Birche De Carvalho', gender: 'F'});
CREATE (a:Author{name:'Gabriela Netto Guerra', gender: 'F'});
CREATE (a:Author{name:'Bruno Werneck Pinto Hoelz', gender: 'M'});
CREATE (a:Author{name:'Wosley Arruda', gender: 'M'});
CREATE (a:Author{name:'Daniel Silva Souza', gender: 'M'});
CREATE (a:Author{name:'Tainá Raiol', gender: 'F'});
CREATE (a:Author{name:'Marcelo De Macedo Brígido', gender: 'M'});
CREATE (a:Author{name:'Peter Florian Stadler', gender: 'M'});
CREATE (a:Author{name:'Renata Mendes De Araújo', gender: 'F'});
CREATE (a:Author{name:'Alexandre Graeml', gender: 'M'});
CREATE (a:Author{name:'Alexandre Cidral', gender: 'M'});
CREATE (a:Author{name:'Rafael Marconi Ramos', gender: 'M'});
CREATE (a:Author{name:'Edison Ishikawa', gender: 'M'});
CREATE (a:Author{name:'Cauê Zaghetto', gender: 'M'});
CREATE (a:Author{name:'Luiz Henrique Morais Aguiar', gender: 'M'});
CREATE (a:Author{name:'Vanessa Tavares Nunes', gender: 'F'});
CREATE (a:Author{name:'Flávia Maria Santoro', gender: 'F'});
CREATE (a:Author{name:'Cláudia Maria Lima Werner', gender: 'F'});
CREATE (a:Author{name:'Luiza Aguiar Hansen', gender: 'F'});
CREATE (a:Author{name:'José Pergentino Araujo Neto', gender: 'M'});
CREATE (a:Author{name:'Donald Matthew Pianto', gender: 'M'});
CREATE (a:Author{name:'Paulo Sérgio Rosa', gender: 'M'});
CREATE (a:Author{name:'Ivan Ricardo Gartner', gender: 'M'});
CREATE (a:Author{name:'Denis José S. Albuquerque', gender: 'M'});
CREATE (a:Author{name:'Claudia Cappelli', gender: 'F'});
CREATE (a:Author{name:'Tiago Henrique Faccio Segato', gender: 'M'});
CREATE (a:Author{name:'Sérgio Eduardo Soares Fernandes', gender: 'M'});
CREATE (a:Author{name:'Jonathan M. Dealmeida', gender: 'M'});
CREATE (a:Author{name:'Luiz A. Dasilva', gender: 'M'});
CREATE (a:Author{name:'Cristiano Bonato Both', gender: 'M'});
CREATE (a:Author{name:'Guido Dutra De Oliveira', gender: 'M'});
CREATE (a:Author{name:'Pedro Phelipe Gonçalves Porto', gender: 'M'});
CREATE (a:Author{name:'Conceição De Maria Albuquerque Alves', gender: 'F'});
CREATE (a:Author{name:'Camila F. T. Pontes', gender: 'F'});
CREATE (a:Author{name:'Luiz Dasilva', gender: 'M'});
CREATE (a:Author{name:'João José Da Costa Gondim', gender: 'M'});
CREATE (a:Author{name:'Airton Marco Polidorio', gender: 'M'});
CREATE (a:Author{name:'Edvaldo Bispo', gender: 'M'});
CREATE (a:Author{name:'Robert B Fisher', gender: 'M'});
CREATE (a:Author{name:'Alceu De Souza Britto Jr', gender: 'M'});
CREATE (a:Author{name:'Cínthia O. De Freitas', gender: 'F'});
CREATE (a:Author{name:'Edson Justino', gender: 'M'});
CREATE (a:Author{name:'Jacques Facon', gender: 'M'});
CREATE (a:Author{name:'Flávio Bortolozzi', gender: 'M'});
CREATE (a:Author{name:'Robert Sabourin', gender: 'M'});
CREATE (a:Author{name:'Cristiane Bastos Rocha Ferreira', gender: 'F'});
CREATE (a:Author{name:'Vivian Bellini Lasca', gender: 'F'});
CREATE (a:Author{name:'David Menotti Gomes', gender: 'M'});
CREATE (a:Author{name:'Luiz Marcelo Ferreira Sirotheau Serique', gender: 'M'});
CREATE (a:Author{name:'Osmar Abílio De Carvalho Junior', gender: 'M'});
CREATE (a:Author{name:'Samuel T. C. De M. Guedes', gender: 'M'});
CREATE (a:Author{name:'Abadia R. Nascimento', gender: 'F'});
CREATE (a:Author{name:'Pedro Melo-pinto', gender: 'M'});
CREATE (a:Author{name:'Rafael D. F. Feitosa', gender: 'M'});
CREATE (a:Author{name:'Vinícius Araújo Santos', gender: 'M'});
CREATE (a:Author{name:'Leandro L Galdino De Oliveira', gender: 'M'});
CREATE (a:Author{name:'Lucas Calabrez Pereyra', gender: 'M'});
CREATE (a:Author{name:'Adriano Soares De Oliveira Bailão', gender: 'M'});
CREATE (a:Author{name:'Marta R. P. Flores', gender: 'F'});
CREATE (a:Author{name:'Rodolfo F. H. Melani', gender: 'M'});
CREATE (a:Author{name:'Marco Aurélio Guimarães', gender: 'M'});
CREATE (a:Author{name:'Carlos E P Machado', gender: 'M'});
CREATE (a:Author{name:'Gerardo A. Idrobo-pizo', gender: 'M'});
CREATE (a:Author{name:'José Maurício S.t. Motta', gender: 'M'});
CREATE (a:Author{name:'Diego De Oliveira Lélis', gender: 'M'});
CREATE (a:Author{name:'Adão Nunes Alves', gender: 'M'});
CREATE (a:Author{name:'Witenberg S.r. Souza', gender: '?'});
CREATE (a:Author{name:'Osmar Luiz Ferreira De Carvalho', gender: 'M'});
CREATE (a:Author{name:'Anesmar Olino De Albuquerque', gender: '?'});
CREATE (a:Author{name:'Pablo Pozzobon De Bem', gender: 'M'});
CREATE (a:Author{name:'Cristiano Rosa Silva', gender: 'M'});
CREATE (a:Author{name:'Pedro Henrique Guimarães Ferreira', gender: 'M'});
CREATE (a:Author{name:'Rebeca Dos Santos De Moura', gender: 'F'});
CREATE (a:Author{name:'Roberto Arnaldo Trancoso Gomes', gender: 'M'});
CREATE (a:Author{name:'Ronei Delfino Da Fonseca', gender: 'M'});
CREATE (a:Author{name:'Paulo Roberto Do Santos', gender: 'M'});
CREATE (a:Author{name:'Melissa Silva Monteiro', gender: 'F'});
CREATE (a:Author{name:'Luciana Alves Fernandes', gender: 'F'});
CREATE (a:Author{name:'Andreia Henrique Campos', gender: 'F'});
CREATE (a:Author{name:'Suélia De Siqueira Rodrigues Fleury Rosa', gender: 'F'});
CREATE (a:Author{name:'Juan S. Toquica', gender: 'M'});
CREATE (a:Author{name:'Patrícia S. Oliveira', gender: 'F'});
CREATE (a:Author{name:'Concepta Mcmanus', gender: 'F'});
CREATE (a:Author{name:'Rubens De Castro Pereira', gender: 'M'});
CREATE (a:Author{name:'Diego Alves Da Silva', gender: 'M'});
CREATE (a:Author{name:'Cristiane Lemes Hamawaki', gender: 'F'});
CREATE (a:Author{name:'Breno Cezar Marinho Juliatti', gender: 'M'});
CREATE (a:Author{name:'Lucas Dos Santos Nascimento', gender: 'M'});
CREATE (a:Author{name:'Osvaldo Toshiyuki Hamawaki', gender: 'M'});
CREATE (a:Author{name:'Fernando Cezar Juliatti', gender: 'M'});
CREATE (a:Author{name:'Ana Paula Oliveira Nogueira', gender: 'F'});
CREATE (a:Author{name:'Rafael Timóteo De Sousa Júnior', gender: 'M'});
CREATE (a:Author{name:'Robson De Oliveira Albuquerque', gender: 'M'});
CREATE (a:Author{name:'Rhandy Rafhael De Carvalho', gender: '?'});
CREATE (a:Author{name:'Hiro Gabriel Cerqueira Ferreira', gender: 'M'});
CREATE (a:Author{name:'Lucas Lima', gender: 'M'});
CREATE (a:Author{name:'Thiago Mael De Castro', gender: 'M'});
CREATE (a:Author{name:'Ricardo Fernandes', gender: 'M'});
CREATE (a:Author{name:'Alisson Palmeira', gender: 'F'});
CREATE (a:Author{name:'Uirá Kulesza', gender: 'M'});
CREATE (a:Author{name:'Dyego Alves Da Silva', gender: 'M'});
CREATE (a:Author{name:'Edgard Costa Oliveira', gender: 'M'});
CREATE (a:Author{name:'Eliakim Zacarias', gender: 'M'});
CREATE (a:Author{name:'Luciano R. De Almeida', gender: 'M'});
CREATE (a:Author{name:'Juliano B. Prettz', gender: 'M'});
CREATE (a:Author{name:'João Paulo C.l. Da Costa', gender: 'M'});
CREATE (a:Author{name:'Edison Pignaton De Freitas', gender: 'M'});
CREATE (a:Author{name:'Ruyther Parente Da Costa', gender: 'M'});
CREATE (a:Author{name:'Caíque De Paula Pereira', gender: 'M'});
CREATE (a:Author{name:'Alexandre Pinheiro', gender: 'M'});
CREATE (a:Author{name:'Luis Javier García Villalba', gender: 'M'});
CREATE (a:Author{name:'Tai-hoon Kim', gender: '?'});
CREATE (a:Author{name:'Giovanni Santos', gender: 'M'});
CREATE (a:Author{name:'Leticia Leite', gender: 'F'});
CREATE (a:Author{name:'Angela Maria Cristina Clara', gender: 'F'});
CREATE (a:Author{name:'Alberto Leite Câmara', gender: 'M'});
CREATE (a:Author{name:'Rejane Maria Da Costa Figueiredo', gender: 'F'});
CREATE (a:Author{name:'Heloise Acco Tives Leão', gender: 'F'});
CREATE (a:Author{name:'Sergio Freitas', gender: 'M'});
CREATE (a:Author{name:'Dionlan Alves De Jesus', gender: '?'});
CREATE (a:Author{name:'Rodrigo César Santos Felisdório', gender: 'M'});
CREATE (a:Author{name:'Yago Luiz Dos Santos', gender: 'M'});
CREATE (a:Author{name:'Vinícius Gomes Ferreira', gender: 'M'});
CREATE (a:Author{name:'Madianita Bogo', gender: '?'});
CREATE (a:Author{name:'Fabiano Fagundes', gender: 'M'});
CREATE (a:Author{name:'José Antonio Siqueira De Cerqueira', gender: 'M'});
CREATE (a:Author{name:'Luis Henrique Vieira Amaral', gender: 'M'});
CREATE (a:Author{name:'Moramay Coutinho', gender: '?'});
CREATE (a:Author{name:'Georges Daniel Amvame Nze', gender: 'M'});
CREATE (a:Author{name:'Hugo Martins', gender: 'M'});
CREATE (a:Author{name:'Antônio Carvalho De Oliveira Junior', gender: 'M'});
CREATE (a:Author{name:'Ricardo Ajax Dias Kosloski', gender: 'M'});
CREATE (a:Author{name:'Roberto Avila Paldês', gender: 'M'});
CREATE (a:Author{name:'José Augusto De Almeida Junior', gender: 'M'});
CREATE (a:Author{name:'William Ferreira Giozza', gender: 'M'});
CREATE (a:Author{name:'Demétrio Antônio Da Silva Filho', gender: 'M'});
CREATE (a:Author{name:'Angélica Toffano Seidel Calazans', gender: 'F'});
CREATE (a:Author{name:'Eloisa Toffano Seidel Masson', gender: 'F'});
CREATE (a:Author{name:'Pedro Henrique Teixeira Costa', gender: 'M'});
CREATE (a:Author{name:'Fernanda Lima', gender: 'F'});
CREATE (a:Author{name:'Bruno Cordeiro Mendes', gender: 'M'});
CREATE (a:Author{name:'Ana Paula Morais Do Vale', gender: 'F'});
CREATE (a:Author{name:'Rafael Leite Patrão', gender: 'M'});
CREATE (a:Author{name:'Leomar Camargo De Souza', gender: 'M'});
CREATE (a:Author{name:'Rogério Machado Gravina', gender: 'M'});
CREATE (a:Author{name:'Vinicius Eloy Dos Reis', gender: 'M'});
CREATE (a:Author{name:'Fábio Lúcio Lopes Mendonça', gender: 'M'});
CREATE (a:Author{name:'Walter Lucas Monteiro De Mendonça', gender: 'M'});
CREATE (a:Author{name:'José Fortes', gender: 'M'});
CREATE (a:Author{name:'Francisco Vitor Lopes', gender: 'M'});
CREATE (a:Author{name:'Diego Marcilio', gender: 'M'});
CREATE (a:Author{name:'João Saraiva', gender: 'M'});
CREATE (a:Author{name:'Márcio Aurélio De Souza Fernandes', gender: 'M'});
CREATE (a:Author{name:'Fernando Gonçalves De Oliveira', gender: 'M'});
CREATE (a:Author{name:'Felipe Silva Ferraz', gender: 'M'});
CREATE (a:Author{name:'Daniel Alves Da Silva', gender: 'M'});
CREATE (a:Author{name:'Sammara Ellen Renner Ferrao', gender: 'F'});
CREATE (a:Author{name:'Artur Potiguara Carvalho', gender: 'M'});
CREATE (a:Author{name:'Alana Paula Barbosa Mota', gender: 'F'});
CREATE (a:Author{name:'Anderson Jefferson Cerqueira', gender: 'M'});
CREATE (a:Author{name:'Renato Carauta Ribeiro', gender: 'M'});
CREATE (a:Author{name:'Murilo Góes De Almeida', gender: 'M'});
CREATE (a:Author{name:'Jhemeson Silva Mota', gender: 'M'});
CREATE (a:Author{name:'Adriana Lopes Damian', gender: 'F'});
CREATE (a:Author{name:'Clarisse Sieckenius De Souza', gender: 'F'});
CREATE (a:Author{name:'Tayana Uchôa Conte', gender: 'F'});
CREATE (a:Author{name:'Remis Balaniuk', gender: 'M'});
CREATE (a:Author{name:'Valério Aymoré Martins', gender: 'M'});
CREATE (a:Author{name:'Vanessa Coelho Ribeiro', gender: 'F'});
CREATE (a:Author{name:'Lucas Alexandre Carvalho Chaves', gender: 'M'});
CREATE (a:Author{name:'Felipe Alberto Moreira Dias', gender: 'M'});
CREATE (a:Author{name:'Ana Lucila Sandoval Orozco', gender: 'F'});
CREATE (a:Author{name:'Joni Da Silva Fraga', gender: 'F'});
CREATE (a:Author{name:'Alysson Neves Bessani', gender: 'M'});
CREATE (a:Author{name:'Miguel Correia', gender: 'M'});
CREATE (a:Author{name:'Fernando Pereira', gender: 'M'});
CREATE (a:Author{name:'Alysson N Bessani', gender: 'M'});
CREATE (a:Author{name:'Fabíola Greve', gender: 'F'});
CREATE (a:Author{name:'Luis Alberto Belem Pacheco', gender: 'M'});
CREATE (a:Author{name:'Rodrigo Saramago', gender: 'M'});
CREATE (a:Author{name:'Tuanir Rezende', gender: '?'});
CREATE (a:Author{name:'Lásaro Jonas Camargos', gender: 'M'});
CREATE (a:Author{name:'Caio Yuri Silva Costa', gender: 'M'});
CREATE (a:Author{name:'Edson Floriano Junior', gender: 'M'});
CREATE (a:Author{name:'Diego F. Aranha', gender: 'M'});
CREATE (a:Author{name:'Hylson Netto', gender: '?'});
CREATE (a:Author{name:'Caio Pereira Oliveira', gender: 'M'});
CREATE (a:Author{name:'Luciana De Oliveira Rech', gender: 'F'});
CREATE (a:Author{name:'Ranyelson N. Carvalho', gender: '?'});
CREATE (a:Author{name:'Alessandro Lima', gender: 'M'});
CREATE (a:Author{name:'Alberto Schaeffer-filho', gender: 'M'});
CREATE (a:Author{name:'Luciano Paschoal Gaspary', gender: 'M'});
CREATE (a:Author{name:'Weverton Cordeiro', gender: 'M'});
CREATE (a:Author{name:'Jonatas A. Marques', gender: 'M'});
CREATE (a:Author{name:'Michel S. Bonfim', gender: 'M'});
CREATE (a:Author{name:'Anderson S. Da Silva', gender: 'M'});
CREATE (a:Author{name:'Diego A. L. Cordoba', gender: 'M'});
CREATE (a:Author{name:'Carla Maria Chagas Cavalcante Koike', gender: 'F'});
CREATE (a:Author{name:'Dianne Magalhães Viana', gender: 'F'});
CREATE (a:Author{name:'Carlos Eduardo Palhares Machado', gender: 'M'});
CREATE (a:Author{name:'Matteo D. Gallidabino', gender: 'M'});
CREATE (a:Author{name:'Gustavo H. M. De Arruda', gender: 'M'});
CREATE (a:Author{name:'Ricardo H. A. Da Silva', gender: 'M'});
CREATE (a:Author{name:'Bianca Marques Santiago', gender: 'F'});
CREATE (a:Author{name:'Laise Nascimento Correa Lima', gender: 'F'});
CREATE (a:Author{name:'Paola Sampaio Gonzales', gender: 'F'});
CREATE (a:Author{name:'Ademir Franco', gender: 'M'});
CREATE (a:Author{name:'Inmaculada Aleman Aguilera', gender: 'F'});
CREATE (a:Author{name:'Lucas Faria Porto', gender: 'M'});
CREATE (a:Author{name:'Andrea Valsecchi', gender: 'F'});
CREATE (a:Author{name:'Oscar Ibanez', gender: 'M'});
CREATE (a:Author{name:'Ana Paula G. S. Almeida', gender: 'F'});
CREATE (a:Author{name:'Joaquin Salas', gender: 'M'});
CREATE (a:Author{name:'Francisco Martínez-trinidad', gender: 'M'});
CREATE (a:Author{name:'Alexandre Raphael Deitos', gender: 'M'});
CREATE (a:Author{name:'Tânia Passarinho', gender: 'F'});
CREATE (a:Author{name:'Eduardo Daruge Jr', gender: 'M'});
CREATE (a:Author{name:'Luiz Francesquini Júnior', gender: 'M'});
CREATE (a:Author{name:'Pedro Silva', gender: 'M'});
CREATE (a:Author{name:'Eduardo José Da Silva Luz', gender: 'M'});
CREATE (a:Author{name:'Guilherme Silva', gender: 'M'});
CREATE (a:Author{name:'Gladston Moreira', gender: 'M'});
CREATE (a:Author{name:'Elizabeth F. Wanner', gender: 'F'});
CREATE (a:Author{name:'Thulio Noslen S. Santos', gender: 'M'});
CREATE (a:Author{name:'Marcus Vinícius Lamar', gender: 'M'});
CREATE (a:Author{name:'Patrick Thevissen', gender: 'M'});
CREATE (a:Author{name:'Andre Da Silva Abade', gender: 'M'});
CREATE (a:Author{name:'Paulo Afonso Ferreira', gender: 'M'});
CREATE (a:Author{name:'Renato Franklin', gender: 'M'});
CREATE (a:Author{name:'Danilo Filgueira Mendonça', gender: 'M'});
CREATE (a:Author{name:'Raian Ali', gender: 'M'});
CREATE (a:Author{name:'Luciano Baresi', gender: 'M'});
CREATE (a:Author{name:'Andre Lanna', gender: 'M'});
CREATE (a:Author{name:'Thiago Castro', gender: 'M'});
CREATE (a:Author{name:'Pierre-yves Schobbens', gender: '?'});
CREATE (a:Author{name:'Sven Apel', gender: 'M'});
CREATE (a:Author{name:'Gabriel S. Rodrigues', gender: 'M'});
CREATE (a:Author{name:'Alessia Knauss', gender: 'F'});
CREATE (a:Author{name:'João Paulo C. De Araújo', gender: 'M'});
CREATE (a:Author{name:'Hugo Andrade', gender: 'M'});
CREATE (a:Author{name:'Arthur Rodrigues', gender: 'M'});
CREATE (a:Author{name:'Caio Batista De Melo', gender: 'M'});
CREATE (a:Author{name:'André Luiz Fernandes Cançado', gender: 'M'});
CREATE (a:Author{name:'Leonardo Pessoa', gender: 'M'});
CREATE (a:Author{name:'Paula Fernandes', gender: 'F'});
CREATE (a:Author{name:'Tullo Tavares', gender: '?'});
CREATE (a:Author{name:'Wagner Meira Junior', gender: 'M'});
CREATE (a:Author{name:'Dorgival Olavo Guedes Neto', gender: 'M'});
CREATE (a:Author{name:'Tony Pan', gender: 'M'});
CREATE (a:Author{name:'Joel H. Saltz', gender: 'M'});
CREATE (a:Author{name:'Timothy D R Hartley', gender: 'M'});
CREATE (a:Author{name:'Umit V. Catalyurek', gender: '?'});
CREATE (a:Author{name:'Lee A.d. Cooper', gender: 'M'});
CREATE (a:Author{name:'Scott Klasky', gender: 'M'});
CREATE (a:Author{name:'Tashin Kurc', gender: '?'});
CREATE (a:Author{name:'Daniel J. Brat', gender: 'M'});
CREATE (a:Author{name:'Fusheng Wang', gender: '?'});
CREATE (a:Author{name:'Jingjing Gao', gender: '?'});
CREATE (a:Author{name:'Lisa Scarpace', gender: 'F'});
CREATE (a:Author{name:'Tom Mikkelsen', gender: 'M'});
CREATE (a:Author{name:'Mattew J. Schniederjan', gender: '?'});
CREATE (a:Author{name:'Carlos S. Moreno', gender: 'M'});
CREATE (a:Author{name:'Eduardo Valle', gender: 'M'});
CREATE (a:Author{name:'Nathan Mariano', gender: 'M'});
CREATE (a:Author{name:'Ricardo Torres', gender: 'M'});
CREATE (a:Author{name:'Yanhui Liang', gender: '?'});
CREATE (a:Author{name:'Darren Treanor', gender: 'M'});
CREATE (a:Author{name:'Derek Magee', gender: 'M'});
CREATE (a:Author{name:'Nick Roberts', gender: 'M'});
CREATE (a:Author{name:'Yangyang Zhu', gender: '?'});
CREATE (a:Author{name:'David Foran', gender: 'M'});
CREATE (a:Author{name:'Xin Qi', gender: '?'});
CREATE (a:Author{name:'Daihou Wang', gender: '?'});
CREATE (a:Author{name:'Michael Nalisnik', gender: 'M'});
CREATE (a:Author{name:'Lin Yang', gender: 'F'});
CREATE (a:Author{name:'Johannes Stegmaier', gender: 'M'});
CREATE (a:Author{name:'Fernando Amat', gender: 'M'});
CREATE (a:Author{name:'William C. Lemon', gender: 'M'});
CREATE (a:Author{name:'Ralf Mikut', gender: 'M'});
CREATE (a:Author{name:'Katie Mcdole', gender: 'F'});
CREATE (a:Author{name:'Yinan Wan', gender: '?'});
CREATE (a:Author{name:'Philipp J. Keller', gender: 'M'});
CREATE (a:Author{name:'Guilherme Andrade', gender: 'M'});
CREATE (a:Author{name:'André Fernandes Freire', gender: 'M'});
CREATE (a:Author{name:'Jeremias Moreira', gender: 'M'});
CREATE (a:Author{name:'Renato Ferreira', gender: 'M'});
CREATE (a:Author{name:'Pengyue Zhang', gender: '?'});
CREATE (a:Author{name:'Mousumi Roy', gender: '?'});
CREATE (a:Author{name:'Hoang Vo', gender: '?'});
CREATE (a:Author{name:'Dejun Teng', gender: '?'});
CREATE (a:Author{name:'Ablimit Aji', gender: '?'});
CREATE (a:Author{name:'Oscar Anacona-mosquera', gender: 'M'});
CREATE (a:Author{name:'Carlos E. Santos', gender: 'M'});
CREATE (a:Author{name:'Felipe Cabral', gender: 'M'});
CREATE (a:Author{name:'Renato C. Sampaio', gender: 'M'});
CREATE (a:Author{name:'Carlos H. Llanos', gender: 'M'});
CREATE (a:Author{name:'Alton B. Farris', gender: 'M'});
CREATE (a:Author{name:'Eduardo Castillo-lion', gender: 'M'});
CREATE (a:Author{name:'Miriam B. Vos', gender: 'F'});
CREATE (a:Author{name:'Rafael Souza', gender: 'M'});
CREATE (a:Author{name:'André Fernandes', gender: 'M'});
CREATE (a:Author{name:'Thiago S.f.x. Teixeira', gender: 'M'});
CREATE (a:Author{name:'Hongxiao Li', gender: '?'});
CREATE (a:Author{name:'Hanyi Yu', gender: '?'});
CREATE (a:Author{name:'Yong-kyu Kim', gender: '?'});
CREATE (a:Author{name:'Yi Jiang', gender: '?'});
CREATE (a:Author{name:'John M. Nickerson', gender: 'M'});
CREATE (a:Author{name:'Hongyi Duanmu', gender: '?'});
CREATE (a:Author{name:'Bruno Ramos Nascimento', gender: 'M'});
CREATE (a:Author{name:'Antonio Ribeiro', gender: 'M'});
CREATE (a:Author{name:'Andre L.s. Meirelles', gender: 'M'});
CREATE (a:Author{name:'Gisele L. Pappa', gender: 'F'});
CREATE (a:Author{name:'Maria Do Carmo Nunes', gender: 'F'});
CREATE (a:Author{name:'Craig Sable', gender: 'M'});
CREATE (a:Author{name:'Andrea Beaton', gender: 'F'});
CREATE (a:Author{name:'Paulo R. Gomes', gender: 'M'});
CREATE (a:Author{name:'Fábio V. Modesto', gender: 'M'});
CREATE (a:Author{name:'Jó Ueyama', gender: '?'});
CREATE (a:Author{name:'Leandro A. Villas', gender: 'M'});
CREATE (a:Author{name:'Alex Pinto', gender: 'M'});
CREATE (a:Author{name:'Vinícius Pereira Gonçalves', gender: 'M'});
CREATE (a:Author{name:'Gustavo Pessin', gender: 'M'});
CREATE (a:Author{name:'Richard W. Pazzi', gender: 'M'});
CREATE (a:Author{name:'Torsten Braun', gender: 'M'});
CREATE (a:Author{name:'Heitor Freitas', gender: 'M'});
CREATE (a:Author{name:'Bruno S. Faiçal', gender: 'M'});
CREATE (a:Author{name:'Pedro Henrique Fini', gender: 'M'});
CREATE (a:Author{name:'Pedro Henrique Gomes', gender: 'M'});
CREATE (a:Author{name:'Jefferson R. Souza', gender: 'M'});
CREATE (a:Author{name:'Fernando S. Osório', gender: 'M'});
CREATE (a:Author{name:'Patrícia A. Vargas', gender: 'F'});
CREATE (a:Author{name:'Denis F. Wolf', gender: 'M'});
CREATE (a:Author{name:'André Carlos Ponde De Leon Ferreira De Carvalho', gender: 'M'});
CREATE (a:Author{name:'Gabriel T Giancristofaro', gender: 'M'});
CREATE (a:Author{name:'Thienne Johnson', gender: 'F'});
CREATE (a:Author{name:'Valéria Carvalho', gender: 'F'});
CREATE (a:Author{name:'Vânia P. De Almeida Neris', gender: 'F'});
CREATE (a:Author{name:'Rodolfo Ipolito Meneguette', gender: 'M'});
CREATE (a:Author{name:'Luiz Fernando Bittencourt', gender: 'M'});
CREATE (a:Author{name:'Daniel Ludovico Guidoni', gender: 'M'});
CREATE (a:Author{name:'Leandro Y. Mano', gender: 'M'});
CREATE (a:Author{name:'Bhaskar Krishnamachari', gender: 'M'});
CREATE (a:Author{name:'Luis H.v. Nakamura', gender: 'M'});
CREATE (a:Author{name:'Giampaolo L. Libralon', gender: 'M'});
CREATE (a:Author{name:'Eduardo P. Costa', gender: 'M'});
CREATE (a:Author{name:'Alan Demétrius Baria Valejo', gender: 'M'});
CREATE (a:Author{name:'Gustavo Furquim', gender: 'M'});
CREATE (a:Author{name:'Roozbeh Jalali', gender: '?'});
CREATE (a:Author{name:'Maria Cristina Ferreira De Oliveira', gender: 'F'});
CREATE (a:Author{name:'Alneu De Andrade Lopes', gender: '?'});
CREATE (a:Author{name:'José R. Torres Neto', gender: 'M'});
CREATE (a:Author{name:'Antonio A F Loureiro', gender: 'M'});
CREATE (a:Author{name:'Celso A. R. L. Brennand', gender: 'M'});
CREATE (a:Author{name:'Guilherme Maia', gender: 'M'});
CREATE (a:Author{name:'Felipe Domingos Da Cunha', gender: 'M'});
CREATE (a:Author{name:'Lucas B. Rondon', gender: 'M'});
CREATE (a:Author{name:'Roger Immich', gender: 'M'});
CREATE (a:Author{name:'Augusto Venancio Neto', gender: 'M'});
CREATE (a:Author{name:'Maycon Leone Maciel Peixoto', gender: 'M'});
CREATE (a:Author{name:'Matheus S Quessada', gender: 'M'});
CREATE (a:Author{name:'Rickson S Pereira', gender: 'M'});
CREATE (a:Author{name:'William Revejes', gender: 'M'});
CREATE (a:Author{name:'Bruno Sartori', gender: 'M'});
CREATE (a:Author{name:'Euclydes N Gottsfritz', gender: 'M'});
CREATE (a:Author{name:'Douglas D Lieira', gender: 'M'});
CREATE (a:Author{name:'Marco Ac Da Silva', gender: 'M'});
CREATE (a:Author{name:'Eduardo M. De Lacerda Filho', gender: 'M'});
CREATE (a:Author{name:'Liriam Michi Enamoto', gender: 'F'});
CREATE (a:Author{name:'Rodrigo Bonacin', gender: 'M'});
CREATE (a:Author{name:'Pollyanna G. Faria Dias', gender: 'F'});
CREATE (a:Author{name:'Mateus C. Silva', gender: 'M'});
CREATE (a:Author{name:'Luciano P. Cota', gender: 'M'});
CREATE (a:Author{name:'Renato A. Nobre', gender: 'M'});
CREATE (a:Author{name:'Khalil C.do Nascimento', gender: 'M'});
CREATE (a:Author{name:'Matheus Schmitz', gender: 'M'});
CREATE (a:Author{name:'Denise Leyi Li', gender: 'F'});
CREATE (a:Author{name:'Tatsuya Hayashi', gender: 'M'});
CREATE (a:Author{name:'Koji Nakano', gender: 'M'});
CREATE (a:Author{name:'Bhuvaneswaran R.s.', gender: '?'});
CREATE (a:Author{name:'Jiagtao Cui', gender: '?'});
CREATE (a:Author{name:'Naohiro Ishii', gender: 'M'});
CREATE (a:Author{name:'Stephan Olariu', gender: 'M'});
CREATE (a:Author{name:'Frank Hsu', gender: 'M'});
CREATE (a:Author{name:'Hong Shen', gender: 'M'});
CREATE (a:Author{name:'Ito Yasuaki', gender: 'F'});
CREATE (a:Author{name:'Oscar Ibarra', gender: 'M'});
CREATE (a:Author{name:'Mohammad Aminul Haq', gender: 'M'});
CREATE (a:Author{name:'Mitsuji Matsumoto', gender: '?'});
CREATE (a:Author{name:'Shinsuke Tanaka', gender: 'M'});
CREATE (a:Author{name:'Thomas Hunziker', gender: 'M'});
CREATE (a:Author{name:'Takashi Ohira', gender: 'M'});
CREATE (a:Author{name:'Makoto Taromaru', gender: 'M'});
CREATE (a:Author{name:'Simone C. Chagas', gender: 'F'});
CREATE (a:Author{name:'Eber Huanca Cayo', gender: 'M'});
CREATE (a:Author{name:'Ruzbeh Shokranian', gender: '?'});
CREATE (a:Author{name:'Nicole Nagel', gender: 'F'});
CREATE (a:Author{name:'Marcos Fagundes Caetano', gender: 'M'});
CREATE (a:Author{name:'Paulo Vieira', gender: 'M'});
CREATE (a:Author{name:'Alex Barbosa', gender: 'M'});
CREATE (a:Author{name:'Paulo Henrique Azevêdo', gender: 'M'});
CREATE (a:Author{name:'Thiago F. Neves', gender: 'M'});
CREATE (a:Author{name:'Lucas De Melo Guimarães', gender: 'M'});
CREATE (a:Author{name:'Ulisses Rodrigues Afonseca', gender: 'M'});
CREATE (a:Author{name:'Felipe M. Modesto', gender: 'M'});
CREATE (a:Author{name:'Juarez Paulino Da Silva Junior', gender: 'M'});
CREATE (a:Author{name:'Lucas Saad N. Nunes', gender: 'M'});
CREATE (a:Author{name:'Yasuaki Ito', gender: 'M'});
CREATE (a:Author{name:'Tatsuya Kawamoto', gender: 'M'});
CREATE (a:Author{name:'Xin Zhou', gender: '?'});
CREATE (a:Author{name:'Hiroaki Kouge', gender: 'M'});
CREATE (a:Author{name:'Takumi Honda', gender: 'M'});
CREATE (a:Author{name:'Toru Fujita', gender: 'M'});
CREATE (a:Author{name:'Camila Feitosa Rêgo', gender: 'F'});
CREATE (a:Author{name:'Heitor Faria', gender: 'M'});
CREATE (a:Author{name:'Rodrigo R. Bezerra', gender: 'M'});
CREATE (a:Author{name:'Hiroki Tokura', gender: 'M'});
CREATE (a:Author{name:'Takahiro Nishimura', gender: 'M'});
CREATE (a:Author{name:'Paulo Victor Farias', gender: 'M'});
CREATE (a:Author{name:'Tulio A. Lima', gender: 'M'});
CREATE (a:Author{name:'Daisuke Takafuji', gender: 'M'});
CREATE (a:Author{name:'Toshiyuki Gotoh', gender: 'M'});
CREATE (a:Author{name:'Satoshi Shima', gender: 'M'});
CREATE (a:Author{name:'Yoichi Tatara', gender: 'M'});
CREATE (a:Author{name:'Motohide Iio', gender: '?'});
CREATE (a:Author{name:'Choken Shu', gender: '?'});
CREATE (a:Author{name:'Helmar Nunes Moreira', gender: 'M'});
CREATE (a:Author{name:'Kevin G. Munhall', gender: 'M'});
CREATE (a:Author{name:'Vincent L. Gracco', gender: 'M'});
CREATE (a:Author{name:'James O. Ramsay', gender: 'M'});
CREATE (a:Author{name:'Laura L. Koenig', gender: 'F'});
CREATE (a:Author{name:'Anders Löfqvist', gender: 'M'});
CREATE (a:Author{name:'Edson Cataldo', gender: 'M'});
CREATE (a:Author{name:'Fabiana R. Leta', gender: 'F'});
CREATE (a:Author{name:'Lucas Nicolato', gender: 'M'});
CREATE (a:Author{name:'Susanne Tainá Ramalho Maciel', gender: 'F'});
CREATE (a:Author{name:'Derek Johns', gender: 'M'});
CREATE (a:Author{name:'W. Einar Mencl', gender: '?'});
CREATE (a:Author{name:'Cristiane Alvarenga Gajo', gender: 'F'});
CREATE (a:Author{name:'Elizabeth Perlman', gender: 'F'});
CREATE (a:Author{name:'Annemie Van Hirtum', gender: 'F'});
CREATE (a:Author{name:'Nicolas Ruty', gender: 'M'});
CREATE (a:Author{name:'Julien Cisonni', gender: 'M'});
CREATE (a:Author{name:'Xavier Pelorson', gender: 'M'});
CREATE (a:Author{name:'Kélem G. Lourenço', gender: 'F'});
CREATE (a:Author{name:'Nicolas Hermant', gender: 'M'});
CREATE (a:Author{name:'Susanne Fuchs', gender: 'F'});
CREATE (a:Author{name:'Bo Wu', gender: 'M'});
CREATE (a:Author{name:'Jean Schoentgen', gender: 'M'});
CREATE (a:Author{name:'Jessy Haas', gender: 'F'});
CREATE (a:Author{name:'Paul Luizard', gender: 'M'});
CREATE (a:Author{name:'Samia Fraj', gender: 'F'});
CREATE (a:Author{name:'Marina Englert', gender: 'F'});
CREATE (a:Author{name:'Glaucya Madazio', gender: 'F'});
CREATE (a:Author{name:'Ingrid Gielow', gender: 'F'});
CREATE (a:Author{name:'Mara Behlau', gender: 'F'});
CREATE (a:Author{name:'Leonardo Wanderley Lopes', gender: 'M'});
CREATE (a:Author{name:'Karoline Evangelista Da Silva', gender: 'F'});
CREATE (a:Author{name:'Deyverson Da Silva Evangelista', gender: 'M'});
CREATE (a:Author{name:'Anna Alice Almeida', gender: 'F'});
CREATE (a:Author{name:'Priscila Oliveira Costa Silva', gender: 'F'});
CREATE (a:Author{name:'Rubens Sampaio', gender: 'M'});
CREATE (a:Author{name:'Christian Soize', gender: 'M'});
CREATE (a:Author{name:'Leonardo Deane De Abreu Sá', gender: 'M'});
CREATE (a:Author{name:'Geraldo Pereira Galvão', gender: 'M'});
CREATE (a:Author{name:'Rute Maria Bevilacqua', gender: 'F'});
CREATE (a:Author{name:'Daniel Jean Roger Nordemann', gender: 'M'});
CREATE (a:Author{name:'Claudio Jorge Pinto Alves', gender: 'M'});
CREATE (a:Author{name:'Nizam Omar', gender: 'M'});
CREATE (a:Author{name:'Maria Cleofé Valverde Ramírez', gender: 'F'});
CREATE (a:Author{name:'Nelson Jesus Ferreira', gender: 'M'});
CREATE (a:Author{name:'Li Hua Shi', gender: '?'});
CREATE (a:Author{name:'Yaeko Yamashita', gender: 'F'});
CREATE (a:Author{name:'Marlon Winston Koendjbiharie', gender: 'M'});
CREATE (a:Author{name:'Ricardo Cezar De Moura Jucá', gender: 'M'});
CREATE (a:Author{name:'Andrew Maciver', gender: 'M'});
CREATE (a:Author{name:'Wesley Martins Teles', gender: 'M'});
CREATE (a:Author{name:'Vinicius Guilherme Fracari Branco', gender: 'M'});
CREATE (a:Author{name:'Fred Freitas', gender: 'M'});
CREATE (a:Author{name:'Bueno B. Souza', gender: 'M'});
CREATE (a:Author{name:'Daniela P. Alves', gender: 'F'});
CREATE (a:Author{name:'Carlos V. De Aquino', gender: 'M'});
CREATE (a:Author{name:'Marcos Vinícius Pinheiro Dib', gender: 'M'});
CREATE (a:Author{name:'Sandro Carlos Vieira', gender: 'M'});
CREATE (a:Author{name:'Marcelo Ladeira', gender: 'M'});
CREATE (a:Author{name:'Cícero Roberto Ferreira De Almeida', gender: 'M'});
CREATE (a:Author{name:'Antonio Pedro Timoszczuk', gender: 'M'});
CREATE (a:Author{name:'Alexandre Gomes De Barros', gender: 'M'});
CREATE (a:Author{name:'Antonio Carlos De Arruda Junior', gender: 'M'});
CREATE (a:Author{name:'Leonardo L. B. V. Cruciol', gender: 'M'});
CREATE (a:Author{name:'Leihong Li', gender: '?'});
CREATE (a:Author{name:'Guiqiu Liu', gender: '?'});
CREATE (a:Author{name:'Kamila B. Nogueira', gender: 'F'});
CREATE (a:Author{name:'Paulo H. C. Aguiar', gender: 'M'});
CREATE (a:Author{name:'Viorel Milea', gender: 'M'});
CREATE (a:Author{name:'Salma Fitouri-trabelsi', gender: 'F'});
CREATE (a:Author{name:'Félix Mora-camino', gender: 'M'});
CREATE (a:Author{name:'Carlos Alberto N. Cosenza', gender: 'M'});
CREATE (a:Author{name:'Xiao-pei Gao', gender: '?'});
CREATE (a:Author{name:'Yi-shang Wu', gender: '?'});
CREATE (a:Author{name:'Vitor Filincowsky Ribeiro', gender: 'M'});
CREATE (a:Author{name:'Juan M. Corchado', gender: 'M'});
CREATE (a:Author{name:'Javier Bajo', gender: 'M'});
CREATE (a:Author{name:'Fei Wu', gender: '?'});
CREATE (a:Author{name:'Tian-cheng Li', gender: '?'});
CREATE (a:Author{name:'Elton Sarmanho Siqueira', gender: 'M'});
CREATE (a:Author{name:'Patrick Kabongo', gender: 'M'});
CREATE (a:Author{name:'Márcio Augusto Da Silva Souza', gender: 'M'});
CREATE (a:Author{name:'Reinaldo Crispiniano Garcia', gender: 'M'});
CREATE (a:Author{name:'Yaming Zhang', gender: '?'});
CREATE (a:Author{name:'Yanyuan Su', gender: '?'});
CREATE (a:Author{name:'Haiou Liu', gender: '?'});
CREATE (a:Author{name:'Yaya H. Koura', gender: '?'});
CREATE (a:Author{name:'Chun Wang', gender: 'F'});
CREATE (a:Author{name:'Thiago Marques Ferreira Crespo', gender: 'M'});
CREATE (a:Author{name:'Alexandre De Barros Barreto', gender: 'M'});
CREATE (a:Author{name:'Chaosheng Tang', gender: '?'});
CREATE (a:Author{name:'Giovani V. Meinerz', gender: 'M'});
CREATE (a:Author{name:'Ana Carolina Lorena', gender: 'F'});
CREATE (a:Author{name:'José A. Sáez', gender: 'M'});
CREATE (a:Author{name:'Julián Luengo', gender: 'M'});
CREATE (a:Author{name:'Francisco Herrera', gender: 'M'});
CREATE (a:Author{name:'Pablo Morales', gender: 'M'});
CREATE (a:Author{name:'Julian Luengo', gender: 'M'});
CREATE (a:Author{name:'Jens Lehmann', gender: 'M'});
CREATE (a:Author{name:'Marcilio C. P. De Souto', gender: 'M'});
CREATE (a:Author{name:'Tin Kam Ho', gender: '?'});
CREATE (a:Author{name:'Adriano Rivolli', gender: 'M'});
CREATE (a:Author{name:'Edesio Alcobaça', gender: 'M'});
CREATE (a:Author{name:'Felipe Siqueira', gender: 'M'});
CREATE (a:Author{name:'Jefferson T. Oliva', gender: 'M'});
CREATE (a:Author{name:'Italo Lopes Oliveira', gender: 'M'});
CREATE (a:Author{name:'Renato Fileto', gender: 'M'});
CREATE (a:Author{name:'René Speck', gender: 'M'});
CREATE (a:Author{name:'Diego Moussallem', gender: 'M'});
CREATE (a:Author{name:'Victor Hugo Barella', gender: 'M'});
CREATE (a:Author{name:'Stan Matwin', gender: 'M'});
CREATE (a:Author{name:'Nicholas Kaminski', gender: 'M'});
CREATE (a:Author{name:'Lisandro Zambenedetti Granville', gender: 'M'});
CREATE (a:Author{name:'Juergen Rochol', gender: 'M'});
CREATE (a:Author{name:'Leonardo Roveda Faganello', gender: 'M'});
CREATE (a:Author{name:'Maicon Kist', gender: 'M'});
CREATE (a:Author{name:'Lucas Bondan', gender: 'M'});
CREATE (a:Author{name:'Juliano Araujo Wickboldt', gender: 'M'});
CREATE (a:Author{name:'Luca Tartarini', gender: 'M'});
CREATE (a:Author{name:'Eduardo Cerqueira', gender: 'M'});
CREATE (a:Author{name:'Mario Gerla', gender: 'M'});
CREATE (a:Author{name:'Paolo Bellavista', gender: 'M'});
CREATE (a:Author{name:'Hamed Ahmadi', gender: 'M'});
CREATE (a:Author{name:'Matias Artur Klafke Schimuneck', gender: 'M'});
CREATE (a:Author{name:'Salvatore D’oro', gender: 'M'});
CREATE (a:Author{name:'Sergio Palazzo', gender: 'M'});
CREATE (a:Author{name:'Manuela Souza', gender: 'F'});
CREATE (a:Author{name:'Matt Bishop', gender: 'M'});
CREATE (a:Author{name:'Jonathan De Almeida', gender: 'M'});
CREATE (a:Author{name:'Valerio Frascolla', gender: 'M'});
CREATE (a:Author{name:'Cristina K. Dominicini', gender: 'F'});
CREATE (a:Author{name:'Marcia H.m. Paiva', gender: 'F'});
CREATE (a:Author{name:'Gilles Caporossi', gender: 'M'});
CREATE (a:Author{name:'Moises R. N. Ribeiro', gender: 'M'});
CREATE (a:Author{name:'Marcelo E. V. Segatto', gender: 'M'});
CREATE (a:Author{name:'Magnos Martinello', gender: 'M'});
CREATE (a:Author{name:'Maxwell E. Monteiro', gender: 'M'});
CREATE (a:Author{name:'Eugênia Thereza G De Oliveira', gender: 'F'});
CREATE (a:Author{name:'João Meidanis', gender: 'M'});
CREATE (a:Author{name:'Zanoni Dias', gender: 'M'});
CREATE (a:Author{name:'Maria Sueli Soares Felipe', gender: 'F'});
CREATE (a:Author{name:'Andrea Maranhão', gender: 'F'});
CREATE (a:Author{name:'Fernando Araripe', gender: 'M'});
CREATE (a:Author{name:'Mauro C Sobrinho', gender: 'M'});
CREATE (a:Author{name:'Eugenia T G Oliveira', gender: 'F'});
CREATE (a:Author{name:'Adilton G Oliveira', gender: 'M'});
CREATE (a:Author{name:'Thelmo E S Martins', gender: 'M'});
CREATE (a:Author{name:'Tiago M Fonseca', gender: 'M'});
CREATE (a:Author{name:'Mauro César Sobrinho', gender: 'M'});
CREATE (a:Author{name:'Marcelo Nardelli P Santana', gender: 'M'});
CREATE (a:Author{name:'Rosângela Vieira Andrade', gender: 'F'});
CREATE (a:Author{name:'Nalvo Franco De Almeida Júnior', gender: 'M'});
CREATE (a:Author{name:'Maria José Albuquerque De Carvalho', gender: 'F'});
CREATE (a:Author{name:'Rede Genoma Centrooeste', gender: '?'});
CREATE (a:Author{name:'Adilton Guedes Oliveira', gender: 'M'});
CREATE (a:Author{name:'Marcus Kiyoshi Inoue', gender: 'M'});
CREATE (a:Author{name:'Daniel Arruda Santos Anjos', gender: 'M'});
CREATE (a:Author{name:'Célia Maria De Alemida Soares', gender: 'F'});
CREATE (a:Author{name:'Silvana Petrofeza Da Silva', gender: 'F'});
CREATE (a:Author{name:'Fernando Araripe G. Torres', gender: 'M'});
CREATE (a:Author{name:'Ildinete Silva Pereira', gender: 'F'});
CREATE (a:Author{name:'Élida Geralda Campos', gender: 'F'});
CREATE (a:Author{name:'Lídia Maria Pepe De Moraes', gender: 'F'});
CREATE (a:Author{name:'Rosália Santos Amorim Jesuino', gender: 'F'});
CREATE (a:Author{name:'Maristela Pereira', gender: 'F'});
CREATE (a:Author{name:'Paula C. S. Ângelo', gender: 'F'});
CREATE (a:Author{name:'Rodrigo Coimbra', gender: 'M'});
CREATE (a:Author{name:'Spartaco Astolfi-filho', gender: 'M'});
CREATE (a:Author{name:'Brazilian Amazon Consortium For Genomic Research (realgene)', gender: '?'});
CREATE (a:Author{name:'Shana Santos', gender: 'F'});
CREATE (a:Author{name:'Márcia Neiva', gender: 'F'});
CREATE (a:Author{name:'Fabricio Barbosa Monteiro Arraes', gender: 'M'});
CREATE (a:Author{name:'Jonso Vieira De Souza', gender: 'M'});
CREATE (a:Author{name:'Gandhi Radis-baptista', gender: 'M'});
CREATE (a:Author{name:'Álvaro R. B. Prieto Da Silva', gender: 'M'});
CREATE (a:Author{name:'Tetsuo Yamane', gender: 'M'});
CREATE (a:Author{name:'Jorge Luis Lopez Lozano', gender: 'M'});
CREATE (a:Author{name:'Mariana Pires De Campos Telles', gender: 'F'});
CREATE (a:Author{name:'Franciele Parreira Peixoto', gender: 'F'});
CREATE (a:Author{name:'Jacqueline Lima', gender: 'F'});
CREATE (a:Author{name:'Lucileide Vilela Resende', gender: 'F'});
CREATE (a:Author{name:'Rosana P Vianello', gender: 'F'});
CREATE (a:Author{name:'Rosane Garcia Collevatti', gender: 'F'});
CREATE (a:Author{name:'Felipe Almeida Lessa', gender: 'M'});
CREATE (a:Author{name:'Taina Raiola Alencar', gender: 'F'});
CREATE (a:Author{name:'Daniele Martins Neto', gender: 'F'});
CREATE (a:Author{name:'Guilherme P Telles', gender: 'M'});
CREATE (a:Author{name:'Rosane Minghim', gender: 'F'});
CREATE (a:Author{name:'Renato De Paula', gender: 'M'});
CREATE (a:Author{name:'Luciana Sa Gomes', gender: 'F'});
CREATE (a:Author{name:'Nalvo Franco Almeida', gender: 'M'});
CREATE (a:Author{name:'Paulo Antonio Alvarez', gender: 'M'});
CREATE (a:Author{name:'Shana Schlottfeldt', gender: 'F'});
CREATE (a:Author{name:'Thannya N. Soares', gender: '?'});
CREATE (a:Author{name:'Rafael D. Loyola', gender: 'M'});
CREATE (a:Author{name:'José Alexandre F. Diniz-filho', gender: 'M'});
CREATE (a:Author{name:'Fernando Araripe Gonçalves Torres', gender: 'M'});
CREATE (a:Author{name:'Marlene Teixeira De-souza', gender: 'F'});
CREATE (a:Author{name:'João Victor A. Oliveira', gender: 'M'});
CREATE (a:Author{name:'Helena Schubert Da Incarnação Lima Silva', gender: 'F'});
CREATE (a:Author{name:'Juliana Capella Orem', gender: 'F'});
CREATE (a:Author{name:'Danilo Andrade Cavalcante', gender: 'M'});
CREATE (a:Author{name:'João Carlos Setubal', gender: 'M'});
CREATE (a:Author{name:'Rodrigo Aniceto', gender: 'M'});
CREATE (a:Author{name:'Rene Xavier', gender: 'M'});
CREATE (a:Author{name:'Valeria Guimarães', gender: 'F'});
CREATE (a:Author{name:'João Victor De Araujo Oliveira', gender: 'M'});
CREATE (a:Author{name:'Fabrizio Costa', gender: 'M'});
CREATE (a:Author{name:'Rolf Backofen', gender: 'M'});
CREATE (a:Author{name:'Jana Hertel', gender: 'F'});
CREATE (a:Author{name:'Lucas Maciel Vieira', gender: 'M'});
CREATE (a:Author{name:'Clicia Grativol', gender: 'F'});
CREATE (a:Author{name:'Flavia Thiebaut', gender: 'F'});
CREATE (a:Author{name:'Thais G Carvalho', gender: 'F'});
CREATE (a:Author{name:'Pablo R Hardoim', gender: 'M'});
CREATE (a:Author{name:'Adriana Hemerly', gender: 'F'});
CREATE (a:Author{name:'Paulo Cavalcanti Gomes Ferreira', gender: 'M'});
CREATE (a:Author{name:'Danilo José Vilar', gender: 'M'});
CREATE (a:Author{name:'Daniel Da Silva Souza', gender: 'M'});
CREATE (a:Author{name:'Maristela Terto Holanda', gender: 'F'});
CREATE (a:Author{name:'Hugo W. Schneider', gender: 'M'});
CREATE (a:Author{name:'Graziela S. Araújo', gender: 'F'});
CREATE (a:Author{name:'Elvismary Molina De Armas', gender: '?'});
CREATE (a:Author{name:'Júlio O. P. Entenza', gender: 'M'});
CREATE (a:Author{name:'Laurent Farinelli', gender: 'M'});
CREATE (a:Author{name:'Cristian Antonio Rojas', gender: 'M'});
CREATE (a:Author{name:'Edmundo P. Da R. Calixto', gender: 'M'});
CREATE (a:Author{name:'Mariana R. Motta', gender: 'F'});
CREATE (a:Author{name:'Helkin G. F. Ballesteros', gender: '?'});
CREATE (a:Author{name:'Barbara Peixoto', gender: 'F'});
CREATE (a:Author{name:'Berenice N. S. De Lima', gender: 'F'});
CREATE (a:Author{name:'Maria Waldl', gender: 'F'});
CREATE (a:Author{name:'Bernhard C. Thiel', gender: 'M'});
CREATE (a:Author{name:'Roman Ochsenreiter', gender: 'M'});
CREATE (a:Author{name:'Alexander Holzenleiter', gender: 'M'});
CREATE (a:Author{name:'Michael T. Wolfinger', gender: 'M'});
CREATE (a:Author{name:'Jakob L. Andersen', gender: 'M'});
CREATE (a:Author{name:'Christoph Flamm', gender: 'M'});
CREATE (a:Author{name:'Calliandra M. De-souza-silva', gender: 'F'});
CREATE (a:Author{name:'André Moraes Nicola', gender: 'M'});
CREATE (a:Author{name:'Anamélia Lorenzetti Bocca', gender: 'F'});
CREATE (a:Author{name:'Patrícia Albuquerque', gender: 'F'});
CREATE (a:Author{name:'Ildinete Silva-pereira', gender: 'F'});
CREATE (a:Author{name:'Fabián Andrés Hurtado', gender: 'M'});
CREATE (a:Author{name:'Aldo Henrique Tavares', gender: 'M'});
CREATE (a:Author{name:'Getúlio P De Oliveira Jr', gender: 'M'});
CREATE (a:Author{name:'Christiane Nishibe', gender: 'F'});
CREATE (a:Author{name:'Daniel Paiva Agustinho', gender: 'M'});
CREATE (a:Author{name:'Rituparno Sem', gender: '?'});
CREATE (a:Author{name:'Jorg Fallmann', gender: 'M'});
CREATE (a:Author{name:'Natasha Andressa Nogueira Jorge', gender: 'F'});
CREATE (a:Author{name:'João Batista De Sousa', gender: 'M'});
CREATE (a:Author{name:'Christopher A Desjardins', gender: 'M'});
CREATE (a:Author{name:'Marcin Grynberg', gender: 'M'});
CREATE (a:Author{name:'Sharvari Gujja', gender: '?'});
CREATE (a:Author{name:'David I. Heiman', gender: 'M'});
CREATE (a:Author{name:'Matthew R Henn', gender: 'M'});
CREATE (a:Author{name:'Chinnappa D Kodira', gender: '?'});
CREATE (a:Author{name:'Henry León-narváez', gender: 'M'});
CREATE (a:Author{name:'Larissa V G Longo', gender: 'F'});
CREATE (a:Author{name:'Li-jun Ma', gender: '?'});
CREATE (a:Author{name:'Iran Malavazi', gender: 'F'});
CREATE (a:Author{name:'Alisson L Matsuo', gender: 'F'});
CREATE (a:Author{name:'Mia D Champion', gender: 'F'});
CREATE (a:Author{name:'Flavia V Morais', gender: 'F'});
CREATE (a:Author{name:'Sabrina Rodríguez-brito', gender: 'F'});
CREATE (a:Author{name:'Sharadha Sakthikumar', gender: '?'});
CREATE (a:Author{name:'Silvia M Salem-izacc', gender: 'F'});
CREATE (a:Author{name:'Sean M Sykes', gender: 'M'});
CREATE (a:Author{name:'Marcus Melo Teixeira', gender: 'M'});
CREATE (a:Author{name:'Milene C Vallejo', gender: 'F'});
CREATE (a:Author{name:'Chandri Yandava', gender: '?'});
CREATE (a:Author{name:'Jason W Holder', gender: 'M'});
CREATE (a:Author{name:'Sarah Young', gender: 'F'});
CREATE (a:Author{name:'Qiandong Zeng', gender: '?'});
CREATE (a:Author{name:'Jeremy Zucker', gender: 'M'});
CREATE (a:Author{name:'Gustavo H Goldman', gender: 'M'});
CREATE (a:Author{name:'Brian J Haas', gender: 'M'});
CREATE (a:Author{name:'Juan G Mcewen', gender: 'M'});
CREATE (a:Author{name:'Gustavo Nino-veja', gender: 'M'});
CREATE (a:Author{name:'Rosana Puccia', gender: 'F'});
CREATE (a:Author{name:'Gioconda San-blas', gender: 'F'});
CREATE (a:Author{name:'Anna Muszewska', gender: 'F'});
CREATE (a:Author{name:'Bruce W Birren', gender: 'M'});
CREATE (a:Author{name:'Christina A Cuomo', gender: 'F'});
CREATE (a:Author{name:'Jonathan Goldberg', gender: 'M'});
CREATE (a:Author{name:'Alexandre M Bailão', gender: 'M'});
CREATE (a:Author{name:'Márcia Eliana Silva Ferreira', gender: 'F'});
CREATE (a:Author{name:'Ana María García Cepero', gender: 'F'});
CREATE (a:Author{name:'Angelo Roncalli Alencar Brayner', gender: 'M'});
CREATE (a:Author{name:'Sergio Vianna Fialho', gender: 'M'});
CREATE (a:Author{name:'Felipe Santos Araujo', gender: 'M'});
CREATE (a:Author{name:'Edilson De Souza Bias', gender: 'M'});
CREATE (a:Author{name:'Jane Adriana', gender: 'F'});
CREATE (a:Author{name:'Ruben Cruz Huacarpuma', gender: 'M'});
CREATE (a:Author{name:'Marcio De Carvalho Victorino', gender: 'M'});
CREATE (a:Author{name:'Marcelo Shiessl', gender: 'M'});
CREATE (a:Author{name:'Marçal De Lima Hokama', gender: 'M'});
CREATE (a:Author{name:'Eduardo Fernandes', gender: 'M'});
CREATE (a:Author{name:'Rommel Novaes Carvalho', gender: 'M'});
CREATE (a:Author{name:'Gustavo Cordeiro Galvão Van Erven', gender: 'M'});
CREATE (a:Author{name:'Harley Vera-olivera', gender: 'M'});
CREATE (a:Author{name:'Leandro Dos Santos Ribeiro', gender: 'M'});
CREATE (a:Author{name:'Thiago Paulo Faleiros', gender: 'M'});
CREATE (a:Author{name:'Aleteia Araujo', gender: 'F'});
CREATE (a:Author{name:'Luiz Martins', gender: 'M'});
CREATE (a:Author{name:'Rodrigo Fonseca', gender: 'M'});
CREATE (a:Author{name:'Eveline Sayao', gender: 'F'});
CREATE (a:Author{name:'George Sand França', gender: 'M'});
CREATE (a:Author{name:'Alexandro Gonçalves', gender: 'M'});
CREATE (a:Author{name:'Ruizhe Guo', gender: '?'});
CREATE (a:Author{name:'Ana Paula Bernardi Da Silva', gender: 'F'});
CREATE (a:Author{name:'Ari Melo Mariano', gender: 'M'});
CREATE (a:Author{name:'Dennis Sávio Silva', gender: 'M'});
CREATE (a:Author{name:'Gabriel F. B. De Medeiros', gender: 'M'});
CREATE (a:Author{name:'Lívia C. Degrossi', gender: 'F'});
CREATE (a:Author{name:'Luiz M. R. Gadelha Jr.', gender: 'M'});
CREATE (a:Author{name:'Cesar Augusto Hurtado Munoz', gender: 'M'});
CREATE (a:Author{name:'Paulo D Conejo', gender: 'M'});
CREATE (a:Author{name:'Alexsandro Fernandes Da Fonseca', gender: 'M'});
CREATE (a:Author{name:'Alison Hugo Rodrigues Silva', gender: 'F'});
CREATE (a:Author{name:'Haydée Werneck Poubel', gender: 'F'});
CREATE (a:Author{name:'José De Siqueira', gender: 'M'});
CREATE (a:Author{name:'Fairouz Kamareddine', gender: '?'});
CREATE (a:Author{name:'Ivan Eid Tavares De Araújo', gender: 'M'});
CREATE (a:Author{name:'Reiner W Hartenstein', gender: 'M'});
CREATE (a:Author{name:'Rinaldi Maya Neto', gender: 'M'});
CREATE (a:Author{name:'Carlos Humberto Llanos Quintero', gender: 'M'});
CREATE (a:Author{name:'Flávio Leonardo Cavalcanti De Moura', gender: 'M'});
CREATE (a:Author{name:'François Monin', gender: 'M'});
CREATE (a:Author{name:'Luis G A Carvalho', gender: 'M'});
CREATE (a:Author{name:'Bruno T De Abreu', gender: 'M'});
CREATE (a:Author{name:'Daniel Muñoz Arboleda', gender: 'M'});
CREATE (a:Author{name:'Rudi Van Els', gender: 'M'});
CREATE (a:Author{name:'André Luiz Galdino', gender: 'M'});
CREATE (a:Author{name:'Daniel Lima Ventura', gender: 'M'});
CREATE (a:Author{name:'Diego F. Sanchéz', gender: 'M'});
CREATE (a:Author{name:'Carlos H Llanos', gender: 'M'});
CREATE (a:Author{name:'Reiner Harsteiner', gender: 'M'});
CREATE (a:Author{name:'José Luis Soncco-álvarez', gender: 'M'});
CREATE (a:Author{name:'Maribel Fernández', gender: 'F'});
CREATE (a:Author{name:'Daniele Nantes Sobrinho', gender: 'F'});
CREATE (a:Author{name:'Andréia Borges Avelar', gender: 'F'});
CREATE (a:Author{name:'Yuri Santos Rego', gender: 'M'});
CREATE (a:Author{name:'Daniel Saad Nogueira Nunes', gender: 'M'});
CREATE (a:Author{name:'Leandro Dos S. Coelho', gender: 'M'});
CREATE (a:Author{name:'Gabriel Marchesan Almeida', gender: 'M'});
CREATE (a:Author{name:'Jürgen Becker', gender: 'M'});
CREATE (a:Author{name:'Murdoch James Gabbay', gender: 'M'});
CREATE (a:Author{name:'Ana Cristina Rocha Oliveira', gender: 'F'});
CREATE (a:Author{name:'Andres Viso', gender: 'M'});
CREATE (a:Author{name:'Eduardo Bonelli', gender: 'M'});
CREATE (a:Author{name:'Washington Luis Ribeiro De Carvalho Segundo', gender: 'M'});
CREATE (a:Author{name:'Thaynara Arielly De Lima', gender: 'F'});
CREATE (a:Author{name:'Juan Edi', gender: 'M'});
CREATE (a:Author{name:'Deivid Vale', gender: 'M'});
CREATE (a:Author{name:'Ariane Alves Almeida', gender: 'F'});
CREATE (a:Author{name:'Gabriel Ferreira Silva', gender: 'M'});
CREATE (a:Author{name:'Chowdary .b. Adsumilli', gender: '?'});
CREATE (a:Author{name:'Marco Carli', gender: 'M'});
CREATE (a:Author{name:'Sanjit K Mitra', gender: '?'});
CREATE (a:Author{name:'John M Foley', gender: 'M'});
CREATE (a:Author{name:'Srinivasa Varadharajan', gender: 'M'});
CREATE (a:Author{name:'Chin C. Koh', gender: 'M'});
CREATE (a:Author{name:'Sanjit Koumar Mitra', gender: '?'});
CREATE (a:Author{name:'Marcelo M. Carvalho', gender: 'M'});
CREATE (a:Author{name:'Marcelo Sampaio Alencar', gender: 'M'});
CREATE (a:Author{name:'Carlos Danilo Miranda Regis', gender: 'M'});
CREATE (a:Author{name:'Raissa Rocha', gender: 'F'});
CREATE (a:Author{name:'Welington Yorihiko Lima Akamine', gender: 'M'});
CREATE (a:Author{name:'Helard Becerra Martinez', gender: '?'});
CREATE (a:Author{name:'Camilo Sánchez-ferreira', gender: 'M'});
CREATE (a:Author{name:'Jones Y. Mori', gender: 'M'});
CREATE (a:Author{name:'Ronaldo Rigoni', gender: 'M'});
CREATE (a:Author{name:'Alexandre Fieno Silva', gender: 'M'});
CREATE (a:Author{name:'Judith Alice Redi', gender: 'F'});
CREATE (a:Author{name:'Jonathan A. Lima', gender: 'M'});
CREATE (a:Author{name:'Cristiano Jacques Miosso', gender: 'M'});
CREATE (a:Author{name:'Luisa Peixoto Eira', gender: 'F'});
CREATE (a:Author{name:'Samuel Soares Santos', gender: 'M'});
CREATE (a:Author{name:'Max E. Vizcarra Melgar', gender: 'M'});
CREATE (a:Author{name:'Helon Vicente Hultmann Ayala', gender: 'M'});
CREATE (a:Author{name:'Andrew Hines', gender: 'M'});
CREATE (a:Author{name:'Felipe B. Silva', gender: 'M'});
CREATE (a:Author{name:'Ricardo Von Borries', gender: 'M'});
CREATE (a:Author{name:'Xiongkuo Min', gender: '?'});
CREATE (a:Author{name:'Guangtao Zhai', gender: '?'});
CREATE (a:Author{name:'Jiantao Zhou', gender: '?'});
CREATE (a:Author{name:'Alan Conrad Bovik', gender: 'M'});
CREATE (a:Author{name:'Gustavo M.s. Nunes', gender: 'M'});
CREATE (a:Author{name:'Fernanda Oliveira', gender: 'F'});
CREATE (a:Author{name:'José Gabriel R.c. Gomes', gender: 'M'});
CREATE (a:Author{name:'Antonio Petraglia', gender: 'M'});
CREATE (a:Author{name:'Jorge Fernández-berni', gender: 'M'});
CREATE (a:Author{name:'Ricardo Carmona-galan', gender: 'M'});
CREATE (a:Author{name:'Ángel Rodríguez-vázquez', gender: 'M'});
CREATE (a:Author{name:'Alessandro R. Silva', gender: 'M'});
CREATE (a:Author{name:'Rafael Diniz', gender: 'M'});
CREATE (a:Author{name:'Ghulam Jillani Ansari', gender: 'M'});
CREATE (a:Author{name:'Jamal Hussain Shah', gender: 'M'});
CREATE (a:Author{name:'Muhammad Sharif', gender: 'M'});
CREATE (a:Author{name:'Nauman Qadeer', gender: '?'});
CREATE (a:Author{name:'Habib Ullah Khan', gender: 'M'});
CREATE (a:Author{name:'Yong Ding', gender: 'M'});
CREATE (a:Author{name:'Kunkai Su', gender: '?'});
CREATE (a:Author{name:'Jingwen Xia', gender: '?'});
CREATE (a:Author{name:'Qiang Huang', gender: '?'});
CREATE (a:Author{name:'Weihai Liu', gender: '?'});
CREATE (a:Author{name:'Qinxue Sun', gender: '?'});
CREATE (a:Author{name:'Haibo Dong', gender: '?'});
CREATE (a:Author{name:'Tiannan Guo', gender: '?'});
CREATE (a:Author{name:'Andrey S. Krylov', gender: 'M'});
CREATE (a:Author{name:'Wenjie Liang', gender: '?'});
CREATE (a:Author{name:'Shijian Ruan', gender: '?'});
CREATE (a:Author{name:'Wenbo Xiao', gender: '?'});
CREATE (a:Author{name:'Xueli Bai', gender: '?'});
CREATE (a:Author{name:'Tingbo Liang', gender: '?'});
CREATE (a:Author{name:'Jiayuan Shao', gender: '?'});
CREATE (a:Author{name:'Rui Sun', gender: 'M'});
CREATE (a:Author{name:'Wuwei Tian', gender: '?'});
CREATE (a:Author{name:'Nan Xiang', gender: 'M'});
CREATE (a:Author{name:'Weigang Ge', gender: '?'});
CREATE (a:Author{name:'Xiuming Zhang', gender: '?'});
CREATE (a:Author{name:'Sana Alamgeer', gender: 'F'});
CREATE (a:Author{name:'Muhammad Irshad', gender: 'M'});
CREATE (a:Author{name:'Mikolaj Leszczuk', gender: 'M'});
CREATE (a:Author{name:'Mateusz Hanusiak', gender: 'M'});
CREATE (a:Author{name:'Emmanuel Wyckens', gender: 'M'});
CREATE (a:Author{name:'George Heston', gender: 'M'});
CREATE (a:Author{name:'Paulo Henrique Portela De Carvalho', gender: 'M'});
CREATE (a:Author{name:'Rafael Silva', gender: 'M'});
CREATE (a:Author{name:'Maximiliano Prestes Ceppo', gender: 'M'});
CREATE (a:Author{name:'Tiago Flor Bento', gender: 'M'});
CREATE (a:Author{name:'Luciano Leonel Mendes', gender: 'M'});
CREATE (a:Author{name:'Francisco Valera', gender: 'M'});
CREATE (a:Author{name:'Wheberth Damascena Dias', gender: '?'});
CREATE (a:Author{name:'Gerhard P. Fettweis', gender: 'M'});
CREATE (a:Author{name:'Carlos Sallé Moreno', gender: 'M'});
CREATE (a:Author{name:'Maria Valéria Marquezini', gender: 'F'});
CREATE (a:Author{name:'André Mendes Cavalcante', gender: 'M'});
CREATE (a:Author{name:'Peter Neuhaus', gender: 'M'});
CREATE (a:Author{name:'Jorge Seki', gender: 'M'});
CREATE (a:Author{name:'Nathália Figueiredo Tinoco Aniceto', gender: 'F'});
CREATE (a:Author{name:'Heikki Karvonen', gender: 'M'});
CREATE (a:Author{name:'Ivan Vidal', gender: 'M'});
CREATE (a:Author{name:'Kamisetty Ramamohan Rao', gender: '?'});
CREATE (a:Author{name:'Henrique Malvar', gender: 'M'});
CREATE (a:Author{name:'Truong Quang Nguyen', gender: '?'});
CREATE (a:Author{name:'Eduardo Moscoso Rubino', gender: 'M'});
CREATE (a:Author{name:'Chang Kyoung Choi', gender: 'M'});
CREATE (a:Author{name:'Young Huh', gender: 'F'});
CREATE (a:Author{name:'Reiner Eschbach', gender: 'M'});
CREATE (a:Author{name:'Dinei A. Florencio', gender: 'M'});
CREATE (a:Author{name:'Ronald W. Schafe', gender: 'M'});
CREATE (a:Author{name:'Jiebo Luo', gender: '?'});
CREATE (a:Author{name:'Zhigang Fan', gender: '?'});
CREATE (a:Author{name:'Trac Duy Tran', gender: '?'});
CREATE (a:Author{name:'Marcia G. Ramos', gender: 'F'});
CREATE (a:Author{name:'Peter Fleckenstein', gender: 'M'});
CREATE (a:Author{name:'Raja Balasubramanian', gender: 'M'});
CREATE (a:Author{name:'Wencheng Wu', gender: '?'});
CREATE (a:Author{name:'Lu Gan', gender: '?'});
CREATE (a:Author{name:'Kai-kuang Ma', gender: '?'});
CREATE (a:Author{name:'Hong Man', gender: 'M'});
CREATE (a:Author{name:'Mark J. T. Smith', gender: 'M'});
CREATE (a:Author{name:'Jie Liang', gender: '?'});
CREATE (a:Author{name:'Ramesh Neelsh Neelamani', gender: 'M'});
CREATE (a:Author{name:'Sanjeeb Dash', gender: '?'});
CREATE (a:Author{name:'Richard G. Baraniuk', gender: 'M'});
CREATE (a:Author{name:'Karen Braun', gender: 'F'});
CREATE (a:Author{name:'Robert Loce', gender: 'M'});
CREATE (a:Author{name:'Hae Yom Kim', gender: 'F'});
CREATE (a:Author{name:'Tiago A. Fonseca', gender: 'M'});
CREATE (a:Author{name:'Karen Oliveira', gender: 'F'});
CREATE (a:Author{name:'Thacio G. Scandaroli', gender: 'M'});
CREATE (a:Author{name:'Philip A. Chou', gender: 'M'});
CREATE (a:Author{name:'Xiang Chen', gender: '?'});
CREATE (a:Author{name:'Jenq-neng Hwang', gender: '?'});
CREATE (a:Author{name:'De Meng', gender: '?'});
CREATE (a:Author{name:'Kuan-hui Lee', gender: '?'});
CREATE (a:Author{name:'Fu-ming Yeh', gender: '?'});
CREATE (a:Author{name:'Gustavo Sandri', gender: 'M'});
CREATE (a:Author{name:'Eduardo Pavez', gender: 'M'});
CREATE (a:Author{name:'Antonio Ortega', gender: 'M'});
CREATE (a:Author{name:'Maja Krivokuca', gender: 'F'});
CREATE (a:Author{name:'Evangelos Alexiou', gender: 'M'});
CREATE (a:Author{name:'Irene Viola', gender: 'F'});
CREATE (a:Author{name:'Tomás M. Borges', gender: 'M'});
CREATE (a:Author{name:'Touradj Ebrahimi', gender: '?'});
CREATE (a:Author{name:'André L. Souto', gender: 'M'});
CREATE (a:Author{name:'Victor Hugo Ferreira De Figueiredo', gender: 'M'});
CREATE (a:Author{name:'Sergio Ito', gender: 'M'});
CREATE (a:Author{name:'Luigi Carro', gender: 'M'});
CREATE (a:Author{name:'Maurício Ayala-rincón', gender: 'M'});
CREATE (a:Author{name:'Luis Gustavo Carvalho', gender: 'M'});
CREATE (a:Author{name:'Reiner W. Hartenstein', gender: 'M'});
CREATE (a:Author{name:'Fabricio Nogueira Buzeto', gender: 'M'});
CREATE (a:Author{name:'Carlos Botelho De Paula Filho', gender: 'M'});
CREATE (a:Author{name:'Carla Denise Castanho', gender: 'F'});
CREATE (a:Author{name:'Gilmar Silva Beserra', gender: 'M'});
CREATE (a:Author{name:'José Edil Guimarães De Medeiros', gender: 'M'});
CREATE (a:Author{name:'Heider Marconi Guedes Madureira', gender: 'M'});
CREATE (a:Author{name:'João Lucas De C. Carneiro', gender: 'M'});
CREATE (a:Author{name:'José Camargo Da Costa', gender: 'M'});
CREATE (a:Author{name:'Karin Becker', gender: 'F'});
CREATE (a:Author{name:'Bruno De Souza Costa Pedroso', gender: 'M'});
CREATE (a:Author{name:'Marcelo Soares Pimenta', gender: 'M'});
CREATE (a:Author{name:'Gilvandson Costa Cavalcante', gender: '?'});
CREATE (a:Author{name:'Flávio Ferreira Lima', gender: 'M'});
CREATE (a:Author{name:'Murilo Venturi', gender: 'M'});
CREATE (a:Author{name:'Marina Pinheiro Marques', gender: 'F'});
CREATE (a:Author{name:'Bruno Costa Motta', gender: 'M'});
CREATE (a:Author{name:'Guilherme Dos Anjos Guimarães', gender: 'M'});
CREATE (a:Author{name:'Francisco Carlos Silva Júnior', gender: 'M'});
CREATE (a:Author{name:'Ivan Saraiva', gender: 'M'});
CREATE (a:Author{name:'Eduardo Steiner', gender: 'M'});
CREATE (a:Author{name:'Paulo Masiero', gender: 'M'});
CREATE (a:Author{name:'Alberto Costa Neto', gender: 'M'});
CREATE (a:Author{name:'Márcio Ribeiro', gender: 'M'});
CREATE (a:Author{name:'Carlos Eduardo Pontual', gender: 'M'});
CREATE (a:Author{name:'Paulo Borba Casella', gender: 'M'});
CREATE (a:Author{name:'Fernando Castor', gender: 'M'});
CREATE (a:Author{name:'Roberta Coelho', gender: 'F'});
CREATE (a:Author{name:'Eduardo Figueiredo', gender: 'M'});
CREATE (a:Author{name:'Paulo De Figueiredo Pires', gender: 'M'});
CREATE (a:Author{name:'Flávio Delicato', gender: 'M'});
CREATE (a:Author{name:'Eduardo Piveta', gender: 'M'});
CREATE (a:Author{name:'Carla Silva', gender: 'F'});
CREATE (a:Author{name:'Valter Camargo', gender: 'M'});
CREATE (a:Author{name:'Rosana Braga', gender: 'F'});
CREATE (a:Author{name:'Julio Leite', gender: 'M'});
CREATE (a:Author{name:'Sérgio Soares', gender: 'M'});
CREATE (a:Author{name:'Otávio Lemos', gender: 'M'});
CREATE (a:Author{name:'Nabor Mendonça', gender: 'M'});
CREATE (a:Author{name:'Thaís Batista', gender: 'F'});
CREATE (a:Author{name:'Nélio Cacho', gender: 'M'});
CREATE (a:Author{name:'Lyrene Silva', gender: '?'});
CREATE (a:Author{name:'Arndt Von Staa', gender: 'M'});
CREATE (a:Author{name:'Fábio Fagundes Silveira', gender: 'M'});
CREATE (a:Author{name:'Marco Tulio Valente', gender: 'M'});
CREATE (a:Author{name:'Fernanda Alencar', gender: 'F'});
CREATE (a:Author{name:'Christina Chavez', gender: 'F'});
CREATE (a:Author{name:'Jaelson Castro', gender: 'M'});
CREATE (a:Author{name:'Ricardo Ramos', gender: 'M'});
CREATE (a:Author{name:'Rosangela Penteado', gender: 'F'});
CREATE (a:Author{name:'Cecília Mary Fischer Rubira', gender: 'F'});
CREATE (a:Author{name:'Carlos Lucena', gender: 'M'});
CREATE (a:Author{name:'Claudio Sant’anna', gender: 'M'});
CREATE (a:Author{name:'Fabiano Ferrari', gender: 'M'});
CREATE (a:Author{name:'Mauricio Alférez', gender: 'M'});
CREATE (a:Author{name:'Leopoldo Motta Teixeira', gender: 'M'});
CREATE (a:Author{name:'Paola Rodrigues Godoy Accioly', gender: 'F'});
CREATE (a:Author{name:'Ana Moreira', gender: 'F'});
CREATE (a:Author{name:'João Araújo', gender: 'M'});
CREATE (a:Author{name:'Joilson Abrantes', gender: 'M'});
CREATE (a:Author{name:'Cristiano Ferraz', gender: 'M'});
CREATE (a:Author{name:'Gustavo Pinto', gender: 'M'});
CREATE (a:Author{name:'Marcel Rebouças', gender: 'M'});
CREATE (a:Author{name:'Welder Pinheiro Luz', gender: 'M'});
CREATE (a:Author{name:'Marcos César De Oliveira', gender: 'M'});
CREATE (a:Author{name:'David Lo', gender: 'M'});
CREATE (a:Author{name:'Francisco Handrick Da Costa', gender: 'M'});
CREATE (a:Author{name:'Ismael Medeiros', gender: 'M'});
CREATE (a:Author{name:'Thales Menezes', gender: 'M'});
CREATE (a:Author{name:'João Victor Da Silva', gender: 'M'});
CREATE (a:Author{name:'Ingrid Lorraine Da Silva', gender: 'F'});
CREATE (a:Author{name:'Krishna Narasimhan', gender: 'F'});
CREATE (a:Author{name:'Carlo A. Furia', gender: 'M'});
CREATE (a:Author{name:'Gabriela Csurka', gender: 'F'});
CREATE (a:Author{name:'Florent Perronnin', gender: 'M'});
CREATE (a:Author{name:'Jorge Sánchez', gender: 'M'});
CREATE (a:Author{name:'Josef Kittler', gender: 'M'});
CREATE (a:Author{name:'William Christmas', gender: 'M'});
CREATE (a:Author{name:'David Windridge', gender: 'M'});
CREATE (a:Author{name:'Fei Yan', gender: '?'});
CREATE (a:Author{name:'John Illingworth', gender: 'M'});
CREATE (a:Author{name:'Magda Osman', gender: 'F'});
CREATE (a:Author{name:'Aftab Khan', gender: 'M'});
CREATE (a:Author{name:'Mitko Veta', gender: 'M'});
CREATE (a:Author{name:'Anders Bjorholm Dahl', gender: 'M'});
CREATE (a:Author{name:'Dan Ciresan', gender: 'M'});
CREATE (a:Author{name:'Jürgen Schmidhuber', gender: 'M'});
CREATE (a:Author{name:'Alessandro Giusti', gender: 'M'});
CREATE (a:Author{name:'Luca Maria Gambardella', gender: 'M'});
CREATE (a:Author{name:'Faik Boray Tek', gender: 'M'});
CREATE (a:Author{name:'Thomas Walter', gender: 'M'});
CREATE (a:Author{name:'Ching-wei Wang', gender: '?'});
CREATE (a:Author{name:'Satoshi Kondo', gender: 'M'});
CREATE (a:Author{name:'Bogdan J. Matuszewski', gender: 'M'});
CREATE (a:Author{name:'Paul J. Van Diest', gender: 'M'});
CREATE (a:Author{name:'Frédéric Precioso', gender: 'M'});
CREATE (a:Author{name:'Violet Snell', gender: 'F'});
CREATE (a:Author{name:'Adnan M. Khan', gender: 'M'});
CREATE (a:Author{name:'Nasir M. Rajpoot', gender: 'M'});
CREATE (a:Author{name:'Evdokia Arkoumani', gender: 'F'});
CREATE (a:Author{name:'Miangela M Lacle', gender: '?'});
CREATE (a:Author{name:'Max A. Viergever', gender: 'M'});
CREATE (a:Author{name:'Josien P. W. Pluim', gender: 'F'});
CREATE (a:Author{name:'Stefan M. Willems', gender: 'M'});
CREATE (a:Author{name:'Haibo Wang', gender: '?'});
CREATE (a:Author{name:'Anant Madabhushi', gender: '?'});
CREATE (a:Author{name:'Angel Cruz-roa', gender: 'M'});
CREATE (a:Author{name:'Fabio Gonzalez', gender: 'M'});
CREATE (a:Author{name:'Anders B. L. Larsen', gender: 'M'});
CREATE (a:Author{name:'Jacob S. Vestergaard', gender: 'M'});
CREATE (a:Author{name:'Moacir Antonelli Ponti', gender: 'M'});
CREATE (a:Author{name:'Mateus Riva', gender: 'M'});
CREATE (a:Author{name:'Cemre Zor', gender: 'F'});
CREATE (a:Author{name:'Philip Coleman', gender: 'M'});
CREATE (a:Author{name:'James Woodcock', gender: 'M'});
CREATE (a:Author{name:'Philip J. B. Jackson', gender: 'M'});
CREATE (a:Author{name:'Frank Melchior', gender: 'M'});
CREATE (a:Author{name:'Chris Pike', gender: 'F'});
CREATE (a:Author{name:'Filippo Maria Fazi', gender: 'M'});
CREATE (a:Author{name:'Trevor J. Cox', gender: 'M'});
CREATE (a:Author{name:'Adrian Hilton', gender: 'M'});
CREATE (a:Author{name:'Andreas Franck', gender: 'M'});
CREATE (a:Author{name:'Jon Francombe', gender: 'M'});
CREATE (a:Author{name:'Qingju Liu', gender: '?'});
CREATE (a:Author{name:'Richard J. Hughes', gender: 'M'});
CREATE (a:Author{name:'Dylan Menzies', gender: 'M'});
CREATE (a:Author{name:'Marcos Felipe Simón Gálvez', gender: 'M'});
CREATE (a:Author{name:'Yan Tang', gender: 'M'});
CREATE (a:Author{name:'Wenwu Wang', gender: '?'});
CREATE (a:Author{name:'Philip J.b. Jackson', gender: 'M'});
CREATE (a:Author{name:'Estephan Dazzi Wandekoken', gender: 'M'});
CREATE (a:Author{name:'Roberto Marcondes Cesar Junior', gender: 'M'});
CREATE (a:Author{name:'Luciano Walenty Xavier Cejnog', gender: 'M'});
CREATE (a:Author{name:'Valeria Meirelles Carril Elui', gender: 'F'});
CREATE (a:Author{name:'Ben Tordoff', gender: 'M'});
CREATE (a:Author{name:'David W. Murray', gender: 'M'});
CREATE (a:Author{name:'Rafael Geraldeli Rossi', gender: 'M'});
CREATE (a:Author{name:'Solange Oliveira Rezende', gender: 'F'});
CREATE (a:Author{name:'Lilian Berton', gender: 'F'});
CREATE (a:Author{name:'Jorge Valverde-rebaza', gender: 'M'});
CREATE (a:Author{name:'Pedro Sampaio', gender: 'M'});
CREATE (a:Author{name:'Alexandre Damasceno', gender: 'M'});
CREATE (a:Author{name:'Igor Sampaio', gender: 'M'});
CREATE (a:Author{name:'Geber Ramalho', gender: 'M'});
CREATE (a:Author{name:'Paulo Borba', gender: 'M'});
CREATE (a:Author{name:'Pedro Osandy Alves Matos Júnior', gender: 'M'});
CREATE (a:Author{name:'Leonardo Cole', gender: 'M'});
CREATE (a:Author{name:'Alexandre Torres Vasconcelos', gender: 'M'});
CREATE (a:Author{name:'George Augusto Valença Santos', gender: 'M'});
CREATE (a:Author{name:'Carina Alves', gender: 'F'});
CREATE (a:Author{name:'Nan Niu', gender: 'M'});
CREATE (a:Author{name:'Laís Neves', gender: 'F'});
CREATE (a:Author{name:'Demóstenes Sena', gender: 'M'});
CREATE (a:Author{name:'Paulo Henrique Monteiro Borba', gender: 'M'});
CREATE (a:Author{name:'Lucinéia Turnes', gender: 'F'});
CREATE (a:Author{name:'Tássio Ferreira Vale', gender: 'M'});
CREATE (a:Author{name:'Eduardo Santana De Almeida', gender: 'M'});
CREATE (a:Author{name:'Ricardo De Lima', gender: 'M'});
CREATE (a:Author{name:'Eneias Silva', gender: 'M'});
CREATE (a:Author{name:'Junier Caminha Amorim', gender: 'M'});
CREATE (a:Author{name:'Rohit Gheyi', gender: '?'});
CREATE (a:Author{name:'Beatriz Emiliano M. De Sousa', gender: 'F'});
CREATE (a:Author{name:'Márcio Guimarães', gender: 'M'});
CREATE (a:Author{name:'Leo Fernandes', gender: 'M'});
CREATE (a:Author{name:'Marcelo D amorim', gender: 'M'});
CREATE (a:Author{name:'Baldoino Fonseca Dos Santos Neto', gender: 'M'});
CREATE (a:Author{name:'Maxime Cordy', gender: 'M'});
CREATE (a:Author{name:'José Aldo Silva Da Costa', gender: 'M'});
CREATE (a:Author{name:'Flávio Medeiros', gender: 'M'});
CREATE (a:Author{name:'Alessandro Garcia', gender: 'M'});
CREATE (a:Author{name:'Denise Guliato', gender: 'F'});
CREATE (a:Author{name:'Célia Aparecida Zorzo Barcelos', gender: 'F'});
CREATE (a:Author{name:'Marcos Aurélio Batista', gender: 'M'});
CREATE (a:Author{name:'Thaís Garcia Da Silva', gender: 'F'});
CREATE (a:Author{name:'Armando Augusto Henriques Vieira', gender: 'M'});
CREATE (a:Author{name:'Bernd Hamann', gender: 'M'});
